In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("evdataset.csv")
pd.set_option('display.width' ,1000)
df.head()

                        _id                               sessionID    stationID  spaceID  siteID  clusterID       connectionTime       disconnectTime  kWhDelivered     doneChargingTime             timezone  userID  userID.1  milesRequested  WhPerMile  minutesAvailable                     modifiedAt paymentRequired   requestedDeparture  kWhRequested
0  5c367215f9af8b4639a8f35f  1_1_193_829_2019-01-02 01:00:51.413435  1-1-193-829  AG-1F03       1          1  2019-01-02 01:00:51  2019-01-02 02:39:46        10.143  2019-01-02 02:39:37  America/Los_Angeles   362.0     362.0           120.0      286.0             139.0  Wed, 02 Jan 2019 01:01:10 GMT            True  2019-01-02 03:19:51         34.32
1  5c367245f9af8b4639a8f360  1_1_191_789_2019-01-02 13:39:11.359003  1-1-191-789  AG-4F52       1          1  2019-01-02 13:39:11  2019-01-03 01:19:57         5.871  2019-01-02 15:37:12  America/Los_Angeles   483.0     483.0            29.0      350.0             435.0  Wed, 02 Jan 2019 13:39:29 GMT            True  2019-01-02 20:54:11         10.15
2  5c367245f9af8b4639a8f361  1_1_178_823_2019-01-02 13:44:26.828039  1-1-178-823  AG-1F08       1          1  2019-01-02 13:44:27  2019-01-02 22:37:33        12.094  2019-01-02 19:18:16  America/Los_Angeles   406.0     406.0            40.0      500.0             592.0  Wed, 02 Jan 2019 14:01:23 GMT            True  2019-01-02 23:36:27         20.00
3  5c367245f9af8b4639a8f362  1_1_193_829_2019-01-02 13:47:38.465648  1-1-193-829  AG-1F03       1          1  2019-01-02 13:47:38  2019-01-02 19:01:31         2.425  2019-01-02 15:06:07  America/Los_Angeles  1117.0    1117.0            10.0      400.0             241.0  Wed, 02 Jan 2019 13:47:44 GMT            True  2019-01-02 17:48:38          4.00
4  5c367245f9af8b4639a8f363  1_1_193_819_2019-01-02 13:53:40.716472  1-1-193-819  AG-1F06       1          1  2019-01-02 13:53:41  2019-01-02 21:40:03        14.331  2019-01-02 16:45:46  America/Los_Angeles   651.0     651.0            40.0      400.0             147.0  Wed, 02 Jan 2019 13:53:47 GMT            True  2019-01-02 16:20:41         16.00

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 17411 entries, 0 to 17410
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   _id                 17411 non-null  str
 1   sessionID           17411 non-null  str
 2   stationID           17411 non-null  str
 3   spaceID             17411 non-null  str
 4   siteID              17411 non-null  int64
 5   clusterID           17411 non-null  int64
 6   connectionTime      17411 non-null  str
 7   disconnectTime      17411 non-null  str
 8   kWhDelivered        17411 non-null  float64
 9   doneChargingTime    17135 non-null  str
 10  timezone            17411 non-null  str
 11  userID              16847 non-null  float64
 12  userID.1            16847 non-null  float64
 13  milesRequested      16847 non-null  float64
 14  WhPerMile           16847 non-null  float64
 15  minutesAvailable    16847 non-null  float64
 16  modifiedAt          16847 non-null  str
 17  paymentRequired     16847 non-null  object
 18  requestedDeparture  16847 non-null  str
 19  kWhRequested        16847 non-null  float64
dtypes: float64(7), int64(2), object(1), str(10)
memory usage: 2.7+ MB

In [4]:
columns_to_drop = ['_id', 'sessionID', 'modifiedAt', 'userID.1', 'timezone', 'spaceID']
df_cleaned = df.drop(columns=columns_to_drop)
pd.set_option('display.width' ,1000)
df_cleaned.head()

     stationID  siteID  clusterID       connectionTime       disconnectTime  kWhDelivered     doneChargingTime  userID  milesRequested  WhPerMile  minutesAvailable paymentRequired   requestedDeparture  kWhRequested
0  1-1-193-829       1          1  2019-01-02 01:00:51  2019-01-02 02:39:46        10.143  2019-01-02 02:39:37   362.0           120.0      286.0             139.0            True  2019-01-02 03:19:51         34.32
1  1-1-191-789       1          1  2019-01-02 13:39:11  2019-01-03 01:19:57         5.871  2019-01-02 15:37:12   483.0            29.0      350.0             435.0            True  2019-01-02 20:54:11         10.15
2  1-1-178-823       1          1  2019-01-02 13:44:27  2019-01-02 22:37:33        12.094  2019-01-02 19:18:16   406.0            40.0      500.0             592.0            True  2019-01-02 23:36:27         20.00
3  1-1-193-829       1          1  2019-01-02 13:47:38  2019-01-02 19:01:31         2.425  2019-01-02 15:06:07  1117.0            10.0      400.0             241.0            True  2019-01-02 17:48:38          4.00
4  1-1-193-819       1          1  2019-01-02 13:53:41  2019-01-02 21:40:03        14.331  2019-01-02 16:45:46   651.0            40.0      400.0             147.0            True  2019-01-02 16:20:41         16.00

In [5]:
df_cleaned.info()

<class 'pandas.DataFrame'>
RangeIndex: 17411 entries, 0 to 17410
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   stationID           17411 non-null  str
 1   siteID              17411 non-null  int64
 2   clusterID           17411 non-null  int64
 3   connectionTime      17411 non-null  str
 4   disconnectTime      17411 non-null  str
 5   kWhDelivered        17411 non-null  float64
 6   doneChargingTime    17135 non-null  str
 7   userID              16847 non-null  float64
 8   milesRequested      16847 non-null  float64
 9   WhPerMile           16847 non-null  float64
 10  minutesAvailable    16847 non-null  float64
 11  paymentRequired     16847 non-null  object
 12  requestedDeparture  16847 non-null  str
 13  kWhRequested        16847 non-null  float64
dtypes: float64(6), int64(2), object(1), str(5)
memory usage: 1.9+ MB

In [6]:
df_cleaned.head()

     stationID  siteID  clusterID       connectionTime       disconnectTime  kWhDelivered     doneChargingTime  userID  milesRequested  WhPerMile  minutesAvailable paymentRequired   requestedDeparture  kWhRequested
0  1-1-193-829       1          1  2019-01-02 01:00:51  2019-01-02 02:39:46        10.143  2019-01-02 02:39:37   362.0           120.0      286.0             139.0            True  2019-01-02 03:19:51         34.32
1  1-1-191-789       1          1  2019-01-02 13:39:11  2019-01-03 01:19:57         5.871  2019-01-02 15:37:12   483.0            29.0      350.0             435.0            True  2019-01-02 20:54:11         10.15
2  1-1-178-823       1          1  2019-01-02 13:44:27  2019-01-02 22:37:33        12.094  2019-01-02 19:18:16   406.0            40.0      500.0             592.0            True  2019-01-02 23:36:27         20.00
3  1-1-193-829       1          1  2019-01-02 13:47:38  2019-01-02 19:01:31         2.425  2019-01-02 15:06:07  1117.0            10.0      400.0             241.0            True  2019-01-02 17:48:38          4.00
4  1-1-193-819       1          1  2019-01-02 13:53:41  2019-01-02 21:40:03        14.331  2019-01-02 16:45:46   651.0            40.0      400.0             147.0            True  2019-01-02 16:20:41         16.00

In [7]:

time_cols = ['connectionTime', 'disconnectTime', 'doneChargingTime', 'requestedDeparture']

for col in time_cols:
    df_cleaned[col] = pd.to_datetime(df_cleaned[col], errors='coerce')

df_cleaned['arrival_hour'] = df_cleaned['connectionTime'].dt.hour           
df_cleaned['arrival_day_of_week'] = df_cleaned['connectionTime'].dt.dayofweek  # हफ्ते का कौन सा दिन है (0-6)
df_cleaned['is_weekend'] = df_cleaned['connectionTime'].dt.dayofweek.isin([5, 6]).astype(int) 
df_cleaned['arrival_month'] = df_cleaned['connectionTime'].dt.month         

#  doneChargingTime (Target Variable) 
df_cleaned['actual_charging_time_minutes'] = (df_cleaned['doneChargingTime'] - df_cleaned['connectionTime']).dt.total_seconds() / 60.0

df_cleaned['idle_time_minutes'] = (df_cleaned['disconnectTime'] - df_cleaned['doneChargingTime']).dt.total_seconds() / 60.0
df_cleaned['disconnect_hour'] = df_cleaned['disconnectTime'].dt.hour         

df_cleaned['departure_hour'] = df_cleaned['requestedDeparture'].dt.hour      
df_cleaned = df_cleaned.dropna(subset=['actual_charging_time_minutes', 'idle_time_minutes'])

df_cleaned = df_cleaned.drop(columns=time_cols)

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df_cleaned['stationID'] = le.fit_transform(df_cleaned['stationID'])
display(df_cleaned.head())

   stationID  siteID  clusterID  kWhDelivered  userID  milesRequested  WhPerMile  minutesAvailable paymentRequired  kWhRequested  arrival_hour  arrival_day_of_week  is_weekend  arrival_month  actual_charging_time_minutes  idle_time_minutes  disconnect_hour  departure_hour
0         47       1          1        10.143   362.0           120.0      286.0             139.0            True         34.32             1                    2           0              1                     98.766667           0.150000                2             3.0
1         29       1          1         5.871   483.0            29.0      350.0             435.0            True         10.15            13                    2           0              1                    118.016667         582.750000                1            20.0
2          1       1          1        12.094   406.0            40.0      500.0             592.0            True         20.00            13                    2           0              1                    333.816667         199.283333               22            23.0
3         47       1          1         2.425  1117.0            10.0      400.0             241.0            True          4.00            13                    2           0              1                     78.483333         235.400000               19            17.0
4         43       1          1        14.331   651.0            40.0      400.0             147.0            True         16.00            13                    2           0              1                    172.083333         294.283333               21            16.0

In [9]:
df_cleaned.head()

   stationID  siteID  clusterID  kWhDelivered  userID  milesRequested  WhPerMile  minutesAvailable paymentRequired  kWhRequested  arrival_hour  arrival_day_of_week  is_weekend  arrival_month  actual_charging_time_minutes  idle_time_minutes  disconnect_hour  departure_hour
0         47       1          1        10.143   362.0           120.0      286.0             139.0            True         34.32             1                    2           0              1                     98.766667           0.150000                2             3.0
1         29       1          1         5.871   483.0            29.0      350.0             435.0            True         10.15            13                    2           0              1                    118.016667         582.750000                1            20.0
2          1       1          1        12.094   406.0            40.0      500.0             592.0            True         20.00            13                    2           0              1                    333.816667         199.283333               22            23.0
3         47       1          1         2.425  1117.0            10.0      400.0             241.0            True          4.00            13                    2           0              1                     78.483333         235.400000               19            17.0
4         43       1          1        14.331   651.0            40.0      400.0             147.0            True         16.00            13                    2           0              1                    172.083333         294.283333               21            16.0

In [10]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in ./venv/lib/python3.12/site-packages (1.9.0)
Requirement already satisfied: numpy>=1.24.1 in ./venv/lib/python3.12/site-packages (from scikit-learn) (2.5.0)
Requirement already satisfied: scipy>=1.10.0 in ./venv/lib/python3.12/site-packages (from scikit-learn) (1.18.0)
Requirement already satisfied: joblib>=1.4.0 in ./venv/lib/python3.12/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in ./venv/lib/python3.12/site-packages (from scikit-learn) (2.22.1)
Requirement already satisfied: threadpoolctl>=3.5.0 in ./venv/lib/python3.12/site-packages (from scikit-learn) (3.6.0)

In [11]:
df_cleaned = df_cleaned.drop(columns=['paymentRequired'], errors='ignore')
display(df_cleaned.head())

   stationID  siteID  clusterID  kWhDelivered  userID  milesRequested  WhPerMile  minutesAvailable  kWhRequested  arrival_hour  arrival_day_of_week  is_weekend  arrival_month  actual_charging_time_minutes  idle_time_minutes  disconnect_hour  departure_hour
0         47       1          1        10.143   362.0           120.0      286.0             139.0         34.32             1                    2           0              1                     98.766667           0.150000                2             3.0
1         29       1          1         5.871   483.0            29.0      350.0             435.0         10.15            13                    2           0              1                    118.016667         582.750000                1            20.0
2          1       1          1        12.094   406.0            40.0      500.0             592.0         20.00            13                    2           0              1                    333.816667         199.283333               22            23.0
3         47       1          1         2.425  1117.0            10.0      400.0             241.0          4.00            13                    2           0              1                     78.483333         235.400000               19            17.0
4         43       1          1        14.331   651.0            40.0      400.0             147.0         16.00            13                    2           0              1                    172.083333         294.283333               21            16.0

In [12]:
from sklearn.model_selection import train_test_split

y = df_cleaned['actual_charging_time_minutes']

X = df_cleaned.drop(columns=['actual_charging_time_minutes'])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(df_cleaned.shape)
print(X_train.shape)
print( X_test.shape)

(17135, 17)
(13708, 16)
(3427, 16)

In [13]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np
rf_model = RandomForestRegressor(n_estimators=100, random_state=42)

rf_model.fit(X_train, y_train)

y_pred = rf_model.predict(X_test)

# (Accuracy Metrics)
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)


print(f"Mean Absolute Error (MAE): {mae:.2f} min")
print(f"Root Mean Squared Error (RMSE): {rmse:.2f} min")
print(f"R-squared Score (R2): {r2:.4f}")

Mean Absolute Error (MAE): 22.54 min
Root Mean Squared Error (RMSE): 33.33 min
R-squared Score (R2): 0.9474

In [14]:

results = pd.DataFrame({
    'Actual Time (Min)': y_test.values,
    'Predicted Time (Min)': y_pred
})
print(results.head(10))

   Actual Time (Min)  Predicted Time (Min)
0         531.333333            549.906500
1         125.150000            143.770167
2         150.616667            144.800833
3         114.216667            122.853833
4         173.533333            209.318500
5         250.066667            179.090500
6         217.700000            276.973667
7         122.283333            133.305167
8         319.900000            326.617000
9         271.050000            230.616500

In [15]:
print(X_train.columns.tolist())

['stationID', 'siteID', 'clusterID', 'kWhDelivered', 'userID', 'milesRequested', 'WhPerMile', 'minutesAvailable', 'kWhRequested', 'arrival_hour', 'arrival_day_of_week', 'is_weekend', 'arrival_month', 'idle_time_minutes', 'disconnect_hour', 'departure_hour']

In [16]:
def fast_predict(kWh_needed, miles, wh_per_mile, arrival_hr, available_min):
    input_data = {
        'kWhDelivered': 0.0,
        'userID': 0,
        'milesRequested': miles,
        'WhPerMile': wh_per_mile,
        'minutesAvailable': available_min,
        'kWhRequested': kWh_needed,
        'arrival_hour': arrival_hr,
        'is_weekend': 0,
        'idle_time_minutes': 0,
        'disconnect_hour': arrival_hr + 2,
        'departure_hour': arrival_hr + 2
    }
    
    input_df = pd.DataFrame([input_data])
    input_df = input_df.reindex(columns=X_train.columns, fill_value=0)
    
    pred_minutes = rf_model.predict(input_df)[0]
    return pred_minutes / 60.0
hours = fast_predict(15.0, 40.0, 300.0, 14, 240)
print(f"{hours:.2f} hours required")

2.09 hours required

In [17]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
param_grid = {
    'n_estimators': [100, 200, 300],         
    'max_depth': [10, 20, 30, None],          
    'min_samples_split': [2, 5, 10],          
    'min_samples_leaf': [1, 2, 4],       
    'max_features': ['sqrt', 'log2']        
}


grid_search = GridSearchCV(
    estimator=RandomForestRegressor(random_state=42), 
    param_grid=param_grid, 
    cv=3, 
    n_jobs=-1,     
    verbose=2,     
    scoring='r2'
)


print("Advanced Hyperparameter Tuning ")
grid_search.fit(X_train, y_train)
best_rf = grid_search.best_estimator_
print(grid_search.best_params_)
print(f"R2 Score: {grid_search.best_score_:.4f}")

Advanced Hyperparameter Tuning
Fitting 3 folds for each of 216 candidates, totalling 648 fits
{'max_depth': None, 'max_features': 'sqrt', 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 300}
R2 Score: 0.8786

In [18]:

best_rf = grid_search.best_estimator_
import joblib
joblib.dump(best_rf, 'best_ev_model.joblib')

['best_ev_model.joblib']

In [19]:
import pandas as pd
def fast_predict(kWh_needed, miles, wh_per_mile, arrival_hr, available_min):
    input_data = {
        'kWhDelivered': 0.0,
        'userID': 0,
        'milesRequested': miles,
        'WhPerMile': wh_per_mile,
        'minutesAvailable': available_min,
        'kWhRequested': kWh_needed,
        'arrival_hour': arrival_hr,
        'is_weekend': 0,
        'idle_time_minutes': 0,
        'disconnect_hour': arrival_hr + 2, 
        'departure_hour': arrival_hr + 2
    }
    
    input_df = pd.DataFrame([input_data])
    input_df = input_df.reindex(columns=X_train.columns, fill_value=0)

    pred_minutes = best_rf.predict(input_df)[0]
    return pred_minutes / 60.0

hours = fast_predict(kWh_needed=15.0, miles=40.0, wh_per_mile=300.0, arrival_hr=14, available_min=240)

print(f"acc to model ,{hours:.2f} hours required।")

acc to model ,2.32 hours required।